export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export EDITOR=nvim
export PATH=$HOME/.local/bin:$PATH
export PROJECTS=$HOME/projects

export ANDROID_HOME=$HOME/Android/Sdk
export GO_PATH=$HOME/go
export GO_ROOT=$HOME/.local/go/bin

export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$GO_ROOT
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

export STORAGE=$HOME/.local/servers
mkdir -p $STORAGE


for file in $PROJECTS/base/bash_functions/*; do
	source "$file"
done

if [ -f "$HOME/.local/tokens.sh" ]; then
    source "$HOME/.local/tokens.sh"
fi

if [ -f "$HOME/.local/tokens_manual.sh" ]; then
    source "$HOME/.local/tokens_manual.sh"
fi

alias v=nvim
alias p=python3
alias psql='docker exec -it postgres psql'
alias mongosh='docker exec -it mongo mongosh'

eval `ssh-agent` > /dev/null

if command -v git &>/dev/null; then
	source /usr/share/bash-completion/completions/git
	__git_complete g __git_main
	alias g=git
	alias gq='git commit -am "update" && git push'
	alias gs='git status -b --porcelain=1'
fi

if command -v kubectl &>/dev/null; then
	alias k='kubectl'
	source <(kubectl completion bash)
	complete -o default -F __start_kubectl k
	export KUBE_EDITOR=nvim
fi

if command -v flux &>/dev/null; then
	source <(flux completion bash)
fi

if command -v gh &>/dev/null; then
	source <(gh completion -s bash)
fi

if command -v hcloud &>/dev/null; then
	source <(hcloud completion bash)
fi

if command -v fzf &>/dev/null; then
	source <(fzf --bash)
fi

# Disable XON/XOFF flow control (Ctrl+S and Ctrl+Q)
stty -ixon

# make sure that child processes exit when you leave a shell
shopt -s huponexit

# check to see if we are in tmux if ot start it
# [ -z "$TMUX"  ] && { tmux attach || exec tmux new-session ;}
#
export PS1=':'
if [ -n "$MY_SESSION" ]; then
    PS1="\033[1;35m$MY_SESSION\033[0m$PS1"
fi
