export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export PS1=' '
export EDITOR=nvim
export PATH=$HOME/.local/bin:$PATH
export PROJECTS=$HOME/projects

#only works if installed
export ANDROID_HOME=$HOME/Android/Sdk
export GO_PATH=$HOME/go
export GO_ROOT=$HOME/.local/go/bin

export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$GO_ROOT
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH

source /usr/share/bash-completion/completions/git

for file in $PROJECTS/base/bash_functions/*; do
	source "$file"
done

alias rg='rg --color never'
alias v=nvim
alias p=python3
alias jp=project_choose

if command -v box &>/dev/null; then
	eval "$(register-python-argcomplete box)"
fi

if command -v git &>/dev/null; then
	__git_complete g __git_main
	alias g=git
	alias gq='git commit -am "update" && git push'
	alias gs='git status -b --porcelain=1'
fi

if command -v kubectl &>/dev/null; then
	alias k='kubectl'
	source <(kubectl completion bash)
	complete -o default -F __start_kubectl k
	export KUBE_EDITOR=nvim
fi

if command -v flux &>/dev/null; then
	source <(flux completion bash)
fi

if command -v gh &>/dev/null; then
	source <(gh completion -s bash)
fi

if command -v hcloud &>/dev/null; then
	source <(hcloud completion bash)
fi

if command -v fzf &>/dev/null; then
	source <(fzf --bash)
fi

# make sure that child processes exit when you leave a shell
shopt -s huponexit
[ -z "$TMUX"  ] && { tmux attach || exec tmux new-session ;}
